### PR TITLE
Allow for a generic request sender instead of only allowing Hyper

### PR DESCRIPTION
**Pull request by mthjones**
### Motivation
* Allows users to use clients other than Hyper to send requests if they choose
* Allows users to create their own sender implementation that wraps the existing Hyper one, perhaps to log outgoing requests.
* Lets us drop `yup-hyper-mock` as a dependency, as it was causing dependency version issues. The tests are simplified as a result.

### Breaking Changes
* Errors have changed quite a bit. Error::Internal is gone. Error::Http has been replaced with Error::HttpRequest, which now contains an HttpRequestError instead of a hyper::Error. This is to allow SlackWebRequestSender implementors to only need to implement a conversion of their client's errors into HttpRequestError. In addition, the error enums now contain a non-exhaustive hidden field. This allows future expansion of the enums without needing to make future breaking changes.

cc: @BenTheElder @kiyoto

### CODE REVIEW

**Comment by mthjones** [comment]
I dropped the newtype wrapper and things work fine. The only issue is if the trait in in scope, in which case you should get an ambiguous method call error message on compile, and can use UFCS to call the correct method.

**Comment by BenTheElder** [comment]
Might not be necessary for this PR, but we should probably add an example snippet with hyper somewhere.

I think being flexible on the http client is nice, and having our own mocking is a win. Looks pretty nice to me.

**Comment by BenTheElder** [comment]
Side note: we should probably pick a stable point in all the refactoring soon and get a release out to crates.io soonish, there are a lot of changes since the last release.

**Comment by mthjones** [comment]
Sorry for the delay! Went through a move at the beginning of the month and have been tied up with a few big projects at work. I'm going to resolve the conflict that came up and merge this in tonight. Will cut a `0.15.0` release after merge.

**Pull request merged**
