### PR TITLE
Threads

### PR DESCRIPTION
**Pull request by dten**
support for new threads fields
https://api.slack.com/docs/message-threading

things that bother me:

- `post_message` gained 2 extra args, don't really have much choice without introducing some kind of builder
- Standard message gained some fields that only exist if the message is the message of a `message_replied` subtype message

### CODE REVIEW

**Comment by BenTheElder** [comment]
This looks pretty good to me. I'll review it closer and cut a release with this when I get a chance.

**Comment by mthjones** [comment]
LGTM, thanks! I'm working on some auto-generation stuff right now to hopefully keep this library up to date with Slack's API much better. Hitting a moving target is pretty painful in a static language like Rust. Ideally, no one would have to update this library manually ever, but that would be dependent on Slack releasing real data schemas.

**Comment by dten** [comment]
Auto generation sounds fun. 

Also noticed while trying this sometimes bot messages don't have the subtype bot_message and so the bot_id field is skipped. Their docs don't mention that might happen :(

**Comment by mthjones** [comment]
> Their docs don't mention that might happen :(

Sounds about right, from my experience. As part of the work for autogenerating this library, I'm also producing schema files that I'm hoping Slack could pick up and keep up to date.

**Comment by BenTheElder** [comment]
@mthjones that looks awesome.

I'll get this merged and rolled out in a release soon, but hopefully we will actually switch to the codegen soon, which looks to be shaping up pretty excellently.

Thank you both. 👍

**Comment by BenTheElder** [comment]
I'm sorry that I didn't get around to merging this. Things were a bit busier than I expected and I got behind on this. However, @mthjones looks to have a comprehensive overhaul of the entire api with codegen pretty much ready to go now in #34 as hinted above. I'm tentatively closing this in favor of the overhaul in #34.

Thanks again though! I really appreciate the contributions.

**Pull request closed without merging**
