### PR TITLE
Make thumbnail fields optional

### PR DESCRIPTION
**Pull request by kiyoto**
Fix issue #18

### CODE REVIEW

**Comment by mthjones** [comment]
Could you modify a few of the tests to have scenarios with some of these fields missing?

**Comment by kiyoto** [comment]
@mthjones Done. As it turned out, there were several more thumbnail types that weren't covered by `File` struct. I added those as well. See [Section "Thumbnails" on Slack's doc](https://api.slack.com/types/file)

**Comment by mthjones** [comment]
Thanks! Looks like they've beefed up their documentation on some of this stuff since these were first implemented. Good to see!

I think some of these interfaces could be improved by moving away from direct property translation in the future. For example, instead of needing an optional URL, width and height for every thumb, just having one `Thumbnail` struct to hold all three would be nicer to work with. That can be a future enhancement.

I noticed Travis failed for reasons unrelated to the changes here. Looks like a dependency versioning issue. I'll take a look at that, then re-verify this PR and merge.

**Comment by mthjones** [comment]
Alright, it looks like it's an upstream issue with `yup-hyper-mock`'s dependencies which are unfortunately going to be hard to resolve. I have some work in the pipeline to remove the dependency on `yup-hyper-mock` entirely, so I suppose this is an extra push towards getting that done!

This PR looks fine from a visual check, so I'll merge. Thanks again!

**Comment by kiyoto** [comment]
>I think some of these interfaces could be improved by moving away from direct property translation in the future. For example, instead of needing an optional URL, width and height for every thumb, just having one Thumbnail struct to hold all three would be nicer to work with. That can be a future enhancement.

Yes. I will think about this more + create a new issue and mark it as enhancement. Thanks for the quick review and merge!

**Pull request merged**
