### PR TITLE
Bot icons

### PR DESCRIPTION
**Pull request by tedgkassen**
Looking for your thoughts on this one since ```::optional_struct_or_empty_array``` didn't work quite right without coercing the type it generated. It was being output as ```Optional<BotIcons>``` which does not have a default implementation and therefore wouldn't compile.

### CODE REVIEW

**Comment by dten** [comment]
Hmm, I had the same issue trying it. I decided either we should derive default on it or that there's no actual point deriving it. I went with changing `optional_struct_or_empty_array` to not use default. It doesn't really add anything of value.

**Comment by dten** [comment]
Not sure why your codegen has produced differently ordered code

**Comment by tedgkassen** [comment]
I couldn't tell you. Is the ordering supposed to be guaranteed by something?

**Comment by dten** [comment]
A bit, it puts things in a map before writing them out. Maps are normally ordered.

**Comment by dten** [comment]
this was fixed with e286109ae5e5687fc51e7f37265afecb279fbd90

**Pull request closed without merging**
